import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/ui/nav_bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header>
          <NavBar />
        </header>
        <main>{children}</main>
        <footer className="bg-secondary p-5 text-center text-sm font-semibold tracking-widest text-white">
          Copyright 2024 &copy; The Roman Catholic Archdiocese of Cebu. All
          Rights Reserved.
        </footer>
      </body>
    </html>
  );
}
